version: "3"

services:
  api-server:
    container_name: api-server
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - 8920:3000
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      postgres:
        condition: service_healthy
    tty: true
  postgres:
    container_name: postgres
    image: postgres:15.4
    restart: always
    working_dir: /app
    ports:
      - 8921:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U qr"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - "postgres_data_dev:/var/lib/postgresql"
  caddy:
    image: caddy:2.7.4-alpine
    ports:
      - 8922:80
      - 8933:443
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/config:/config
      - ./caddy/data:/data
volumes:
  postgres_data_dev:
