version: "3"


services:
  api-server:
    container_name: api-server
    build:
      context: .
      args:
        DATABASE_URL: ${DATABASE_URL}
    volumes:
      - .:/app
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
    networks:
      - net
    tty:
      true
  db:
    image: postgres:15
    container_name: postgres
    working_dir: /app
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - "postgres_data_dev:/var/lib/postgresql"
    networks:
      - net
volumes:
  postgres_data_dev:
networks:
  net:
    driver: bridge
