name: Release
on: [push]

jobs:
  push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set tag
        id: set_tag
        run: |
          TAG_NAME="${{ github.ref_name }}"
          CLEANED_TAG_NAME=$(echo "$TAG_NAME" | sed 's/[^a-zA-Z0-9_.-]/-/g')
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "::set-output name=tag::latest"
          else
            echo "::set-output name=tag::$CLEANED_TAG_NAME"
          fi
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ steps.set_tag.outputs.tag }}
